### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/topology/IRichSpout

### ISSUE THREAD

**Issue by ghost** [davidkiss/storm-twitter-word-count#5]
Hi... I'm getting the following error when trying to submit the topology to the nimbus server hosted in Docker environment :

bash-4.3# storm jar /data/topology.jar com.kaviddiss.storm.Topology
Running: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apache-storm-1.1.1 -Dstorm.log.dir=/apache-storm-1.1.1/logs -Djava.library.path=/usr
/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /apache-storm-1.1.1/lib/storm-rename-hack-1.1.1.jar:/apache-storm-1.1.1/lib/asm-5.0.3.jar:/apache-storm-1.1.1/lib/slf4j-api-1.7.21.j
ar:/apache-storm-1.1.1/lib/disruptor-3.3.2.jar:/apache-storm-1.1.1/lib/log4j-api-2.8.2.jar:/apache-storm-1.1.1/lib/ring-cors-0.1.5.jar:/apache-storm-1.1.1/lib/log4j-slf4j-impl-2.8.2.jar:/apa
che-storm-1.1.1/lib/kryo-3.0.3.jar:/apache-storm-1.1.1/lib/minlog-1.3.0.jar:/apache-storm-1.1.1/lib/log4j-over-slf4j-1.6.6.jar:/apache-storm-1.1.1/lib/clojure-1.7.0.jar:/apache-storm-1.1.1/l
ib/objenesis-2.1.jar:/apache-storm-1.1.1/lib/reflectasm-1.10.1.jar:/apache-storm-1.1.1/lib/storm-core-1.1.1.jar:/apache-storm-1.1.1/lib/log4j-core-2.8.2.jar:/apache-storm-1.1.1/lib/servlet-a
pi-2.5.jar:/data/topology.jar:/conf:/apache-storm-1.1.1/bin -Dstorm.jar=/data/topology.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} com.kaviddiss.storm.Topology
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/topology/IRichSpout
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: backtype.storm.topology.IRichSpout
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by ashajjar** [comment]
The current project is using old dependencies, you need to update pom.xml to work on newer version of storm, I had the same issue and solved it [here](https://github.com/ashajjar/storm-twitter-word-count)
